# -*- coding: utf-8 -*-
"""Buy & Sell Stocks II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFYFG4l-qZC6H1GhwLgroNnGp8P7B7xB

You are given an integer array prices where prices[i] is the price of a given stock on the ith day.

On each day, you may decide to buy and/or sell the stock. You can only hold at most one share of the stock at any time. However, you can buy it then immediately sell it on the same day.

Find and return the maximum profit you can achieve.



Example 1:

Input: prices = [7,1,5,3,6,4] <br>
Output: 7 <br>
Explanation:

Buy on day 2 (price = 1) and sell on day 3 (price = 5), profit = 5-1 = 4.
Then buy on day 4 (price = 3) and sell on day 5 (price = 6), profit = 6-3 = 3.<br>
Total profit is 4 + 3 = 7.

Example 2:

Input: prices = [1,2,3,4,5] <br>
Output: 4 <br>
Explanation: Buy on day 1 (price = 1) and sell on day 5 (price = 5), profit = 5-1 = 4.<br>
Total profit is 4.

Example 3:

Input: prices = [7,6,4,3,1] <br>
Output: 0<br>
Explanation: There is no way to make a positive profit, so we never buy the stock to achieve the maximum profit of 0.
"""

prices = [7,1,5,3,6,4]

class Solution:
    def maxProfit(prices):

        total_profit = 0

        for i in range(len(prices)):
            if i < len(prices) - 1:
                if prices[i] > prices[i + 1]:
                    i = i + 1
                else:
                    profit = prices[i + 1] - prices[i]
                    total_profit += profit
        return total_profit

Solution.maxProfit(prices)

"""We are defining a variable to update profit <br>

Using loop, we will check whether the selected element is smaller than the next element or not <br>

if it is, then we will deduct bigger from smaller, otherwise we will increase the i and move the pointer
"""