# -*- coding: utf-8 -*-
"""h Index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFYFG4l-qZC6H1GhwLgroNnGp8P7B7xB

Given an array of integers citations where citations[i] is the number of citations a researcher received for their ith paper, return the researcher's h-index.

According to the definition of h-index on Wikipedia: The h-index is defined as the maximum value of h such that the given researcher has published at least h papers that have each been cited at least h times.



Example 1:

Input: citations = [3,0,6,1,5]

Output: 3

Explanation: [3,0,6,1,5] means the researcher has 5 papers in total and each of them had received 3, 0, 6, 1, 5 citations respectively.
Since the researcher has 3 papers with at least 3 citations each and the remaining two with no more than 3 citations each, their h-index is 3.

Example 2:

Input: citations = [6, 2, 5, 9, 1, 8]
Output: 4

Let's go through the steps to calculate the h-index for the given citation counts [6, 2, 5, 9, 1, 8]:

1. Arrange the citation counts in descending order: [9, 8, 6, 5, 2, 1].
2. Identify the position i of each paper in the sorted list: [1, 2, 3, 4, 5, 6].

Now, find the maximum i such that (c_i >= i):

- For (i = 1): (c_1 = 9 >= 1): (true)
- For (i = 2): (c_2 = 8 >= 2): (true)
- For (i = 3): (c_3 = 6 >= 3): (true)
- For (i = 4): (c_4 = 5 >= 4): (true)
- For (i = 5): (c_5 = 2 >= 5): (false)

The maximum i for which c_i >= i is (i = 4).

Therefore, the h-index for this set of citation counts is 4. This means that the researcher has 4 papers that each have at least 4 citations, and the remaining two papers have fewer citations.
"""

c = [3,0,6,1,5]

c.sort(reverse = True)

h = 0

while h<len(c) and c[h]>h:
  h+=1

print(h)