# -*- coding: utf-8 -*-
"""Is SubSequence.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFYFG4l-qZC6H1GhwLgroNnGp8P7B7xB

Given two strings s and t, return true if s is a subsequence of t, or false otherwise.

A **subsequence** of a string is a *new string that is formed from the original string by deleting some (can be none) of the characters without disturbing the relative positions of the remaining characters.* (i.e., "ace" is a subsequence of "abcde" while "aec" is not).



Example 1:

Input: s = "abc", t = "ahbgdc"

Output: true

Example 2:

Input: s = "axc", t = "ahbgdc"

Output: false
"""

s = "abc"
t = "ahbgdc"

ind = 0

for i in t:

  if ind<len(s) and i == s[ind]:
    ind+=1

print ('True') if ind == len(s) else print ('False')

"""
Here's the explanation of the logic:

1. **Initialization**:
   - `s` is the subsequence we're looking for, and `t` is the string where we're searching for `s`.
   - `ind` is initialized to 0, which represents the index of the current character we're looking for in `s`.

2. **Main Loop**:
   - The loop iterates over each character `i` in the string `t`.
   - Inside the loop, it checks two conditions:
     - Whether `ind` is less than the length of `s`, ensuring that we haven't exceeded the length of the subsequence `s`.
     - Whether the character `i` in `t` matches the character at index `ind` in `s`.
   - If both conditions are met, it means we found a matching character, so we increment `ind` to move to the next character in `s`.

3. **Checking Completion**:
   - After the loop finishes, if `ind` is equal to the length of `s`, it means all characters in `s` have been found in `t`.
   - If `ind` equals the length of `s`, it prints `'True'`, indicating that `s` is a subsequence of `t`. Otherwise, it prints `'False'`.

Let's analyze it with the given strings:

- For `s = "abc"` and `t = "ahbgdc"`:
  - The loop iterates through each character in `t`.
  - It checks if the current character in `t` matches the character at index `ind` in `s`.
  - If there's a match, it moves to the next character in `s`.
  - After the loop, `ind` will be 3, which is equal to the length of `s`.
  - So, it prints `'True'`, indicating that `s` is a subsequence of `t`."""