# -*- coding: utf-8 -*-
"""Majority Element.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y_DwxCl3cPEYaaDMdoqc2-DjhmNwXotD

Given an array nums of size n, return the majority element.

Example

Input

l = [3,3,5,5,6,6,6,8,8,4,4,4,4,4]

Output

4
"""

# Only run this if your max function is not working

from builtins import max

l = [3,3,5,5,6,6,6,8,8,4,4,4,4,4]

x = max(set(l), key = l.count)

x

"""Intuition

To find one line solution

Approach

Create a set to get unique elements from the list.

set(lst)

Find the element in the set with the maximum count based on occurrences in the original list.

max(set(lst), key=lst.count)

Complexity

Time complexity:O(n^2) <br>
Space complexity: O(n)
"""