# -*- coding: utf-8 -*-
"""Remove Element.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xt8wdUkjv-6C2UzOFYRFqCZzs6qRjEBP

You are given an integer array nums and an integer val, remove all occurrences of val in nums in-place.

Example :

Input :            

nums = [0,1,2,2,3,0,4,2]<br>
val = 2

Output :

[0,1,3,0,4]
"""

nums = [0,1,2,2,3,0,4,2]
val = 2

nums[:] = filter(lambda X : X!=val, nums)

nums

"""Intuition
Wanted to find best one line solution

Approach
Solution will check lambda function first <br>
Filter function will filterout all true value received from lambda function<br>
nums[:] will update the original nums immediately

Complexity

Time complexity: O(n)

Space complexity: O(1)
"""